# Generated by Django 5.2.16 on 2026-07-31 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('display_name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('enabled', models.BooleanField(default=True, help_text='У выключенного сборщика сохраняется история и конфигурации, но ничего нового не запускается.', verbose_name='Включён')),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Синхронизирован')),
            ],
            options={
                'verbose_name': 'Сборщик',
                'verbose_name_plural': 'Сборщики',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('domain', models.URLField(help_text='Корень сайта площадки со схемой и без завершающего слэша, например https://bankrupt.centerr.ru.', verbose_name='Домен')),
                ('start_url', models.CharField(blank=True, default='', help_text='Пусто — путь по умолчанию для движка того профиля, который обходит этот сайт.', max_length=200, verbose_name='Путь к листингу')),
                ('tls_options', models.JSONField(blank=True, default=dict, help_text='Редкие костыли под конкретный сайт: доп. сертификат, отключение проверки TLS и подобное.', verbose_name='TLS-настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('collector_key', models.CharField(db_index=True, help_text='Ссылка по ключу. Конкретная версия фиксируется в момент постановки в очередь, а не здесь.', max_length=100, verbose_name='Сборщик')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Исходные параметры как их задал человек. При постановке в очередь они проверяются по схеме сборщика, и уже результат попадает в снимок задачи.', verbose_name='Параметры')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_configs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('source', models.ForeignKey(blank=True, help_text='Сайт, чьи домен/путь листинга/TLS-настройки объединяются с параметрами этого профиля при постановке в очередь. Пусто — у сборщика нет понятия сайта.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='control.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Хост площадки.', max_length=255, verbose_name='Источник')),
                ('lot_id', models.CharField(max_length=255, verbose_name='Идентификатор лота')),
                ('trade_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Идентификатор торга')),
                ('lot_num', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер лота')),
                ('trade_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Номер торга')),
                ('trade_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип торгов')),
                ('debtor', models.TextField(blank=True, default='', verbose_name='Должник')),
                ('organizer', models.TextField(blank=True, default='', verbose_name='Организатор')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('lot_url', models.TextField(blank=True, default='', verbose_name='Ссылка на лот')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('price_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Цена как на сайте')),
                ('status', models.CharField(blank=True, default='', max_length=255, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, help_text='Выведено из статуса самой площадки, а не из присутствия лота в обходе.', verbose_name='Идут торги')),
                ('bidding_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Приём заявок до')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата результатов')),
                ('bidding_date_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Срок как на сайте')),
                ('event_date_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Дата как на сайте')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Документы')),
                ('price_schedule', models.JSONField(blank=True, default=list, verbose_name='График снижения цены')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Прочее с карточки')),
                ('fingerprint', models.CharField(blank=True, default='', help_text='Хэш табличных полей. Совпал — карточка лота не перезапрашивается.', max_length=64, verbose_name='Отпечаток')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Впервые увиден')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='Последний раз увиден')),
                ('last_job_id', models.BigIntegerField(blank=True, help_text='Мягкая ссылка, как и у Job на Config: лоты переживают чистку истории задач.', null=True, verbose_name='Последняя задача')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='lot_by_source_active_idx'), models.Index(fields=['-last_seen_at'], name='lot_by_last_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'lot_id'), name='uniq_lot_per_source')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_key', models.CharField(editable=False, max_length=100, verbose_name='Сборщик')),
                ('effective_parameters', models.JSONField(default=dict, editable=False, help_text='Параметры, разрешённые по схеме сборщика: подставлены умолчания, пройдена проверка. Только *ссылки* на учётные данные — никогда не сами секреты.', verbose_name='Итоговые параметры')),
                ('config_id', models.BigIntegerField(db_index=True, editable=False, help_text='Мягкая ссылка. Внешнего ключа нет намеренно: история задач переживает жизненный цикл конфигурации.', verbose_name='Конфигурация')),
                ('origin', models.CharField(choices=[('manual', 'Вручную'), ('schedule', 'По расписанию')], default='manual', max_length=16, verbose_name='Источник')),
                ('schedule_id', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Расписание')),
                ('fire_time', models.DateTimeField(blank=True, editable=False, help_text='Запланированный момент, который реализует эта задача. Уникален в пределах расписания — именно это ограничение, а не блокировка, делает планирование идемпотентным.', null=True, verbose_name='Момент срабатывания')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='pending', max_length=16, verbose_name='Статус')),
                ('claimed_by', models.CharField(blank=True, default='', max_length=200, verbose_name='Захвачена воркером')),
                ('claimed_until', models.DateTimeField(blank=True, null=True, verbose_name='Аренда до')),
                ('attempt_no', models.PositiveIntegerField(default=0, help_text='Число передач между исполнителями, а не повторов сборщика. Растёт при каждом захвате, включая перехват после истечения аренды.', verbose_name='Попытка')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='Запрошена отмена')),
                ('priority', models.IntegerField(default=0, help_text='Больше — раньше.', verbose_name='Приоритет')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Доступна с')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('structured_error', models.JSONField(blank=True, help_text='{type, message, trace}', null=True, verbose_name='Ошибка')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='{rows, bytes, calls, ...}', verbose_name='Метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['-priority', 'available_at'], name='job_claimable_pending_idx'), models.Index(condition=models.Q(('status', 'running')), fields=['claimed_until'], name='job_expired_lease_idx'), models.Index(fields=['config_id', '-created_at'], name='job_by_config_idx'), models.Index(fields=['status', '-created_at'], name='job_by_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('schedule_id__isnull', False)), fields=('schedule_id', 'fire_time'), name='uniq_job_per_schedule_fire_time')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(help_text='Стандартное cron-выражение из пяти полей.', max_length=100, verbose_name='Cron')),
                ('timezone', models.CharField(default='UTC', help_text='Название по IANA. Моменты запуска считаются в этом поясе, хранятся в UTC.', max_length=64, verbose_name='Часовой пояс')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('skip_if_running', models.BooleanField(default=True, help_text='Не запускать новый экземпляр, пока предыдущий запуск этой конфигурации не завершён. Пропущенное срабатывание не догоняется — считается только ближайшее к текущему моменту.', verbose_name='Пропускать, если ещё выполняется')),
                ('last_fired_at', models.DateTimeField(blank=True, help_text='Сдвигается в той же транзакции, что создаёт задачу.', null=True, verbose_name='Последнее срабатывание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='control.config', verbose_name='Конфигурация')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['config__name', 'cron'],
                'indexes': [models.Index(fields=['enabled'], name='control_sch_enabled_3e94d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['enabled'], name='control_con_enabled_b7774f_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['collector_key'], name='control_con_collect_3d022f_idx'),
        ),
    ]
