# Generated by Django 5.2.16 on 2026-07-28 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True, help_text='Disabled collectors keep their history and their Configs; nothing new runs.')),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('collector_key', models.CharField(db_index=True, help_text='Resolve-by-key. The concrete version is pinned at enqueue time, not here.', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Raw authored parameters. Resolved against the collector version's schema at enqueue; the resolved form is what the Job snapshots.")),
                ('enabled', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False, help_text='Soft delete. An archived config never enqueues.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('last_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', editable=False, max_length=16)),
                ('last_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_job_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_key', models.CharField(editable=False, max_length=100)),
                ('collector_version', models.CharField(editable=False, max_length=32)),
                ('effective_parameters', models.JSONField(default=dict, editable=False, help_text="Raw params resolved through the version's schema: defaults applied, validated. Credential *references* only — never credential values.")),
                ('schema_version', models.IntegerField(default=0, editable=False)),
                ('config_id', models.BigIntegerField(db_index=True, editable=False, help_text='Soft reference. No FK on purpose: Job history outlives Config lifecycle.')),
                ('config_revision', models.PositiveIntegerField(default=0, editable=False)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule')], default='manual', max_length=16)),
                ('schedule_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('fire_time', models.DateTimeField(blank=True, editable=False, help_text='The scheduled occurrence this Job realises. Unique per schedule — that constraint, not a lock, is what makes scheduling idempotent.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('claimed_by', models.CharField(blank=True, default='', max_length=200)),
                ('claimed_until', models.DateTimeField(blank=True, null=True)),
                ('attempt_no', models.PositiveIntegerField(default=0, help_text='Executor handoffs, not collector retries. Incremented by every claim, including a reclaim after a lease expired.')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher runs first.')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('structured_error', models.JSONField(blank=True, help_text='{type, message, trace}', null=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='{rows, bytes, calls, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(help_text='Standard 5-field cron expression.', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text='IANA name. Cron occurrences are computed in this zone, stored in UTC.', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('overlap_policy', models.CharField(choices=[('skip', 'Skip — drop this fire if the previous run is still active'), ('queue', 'Queue — enqueue anyway, it waits behind the active run'), ('allow', 'Allow — enqueue and run concurrently')], default='skip', max_length=16)),
                ('catchup_policy', models.CharField(choices=[('fire_missed', 'Fire missed — enqueue every missed occurrence'), ('skip_to_now', 'Skip to now — enqueue at most the latest occurrence')], default='skip_to_now', max_length=16)),
                ('last_fired_at', models.DateTimeField(blank=True, help_text='Advanced in the same transaction that creates the Job.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='control.config')),
            ],
            options={
                'ordering': ['config__name', 'cron'],
            },
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['archived', 'enabled'], name='control_con_archive_0f4d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['collector_key'], name='control_con_collect_3d022f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['-priority', 'available_at'], name='job_claimable_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'running')), fields=['claimed_until'], name='job_expired_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['config_id', '-created_at'], name='job_by_config_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='job_by_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_id__isnull', False)), fields=('schedule_id', 'fire_time'), name='uniq_job_per_schedule_fire_time'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['enabled'], name='control_sch_enabled_3e94d4_idx'),
        ),
    ]
