# Generated by Django 5.2.16 on 2026-07-28 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collector',
            options={'ordering': ['key'], 'verbose_name': 'Сборщик', 'verbose_name_plural': 'Сборщики'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['config__name', 'cron'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='collector',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='display_name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='enabled',
            field=models.BooleanField(default=True, help_text='У выключенного сборщика сохраняется история и конфигурации, но ничего нового не запускается.', verbose_name='Включён'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Синхронизирован'),
        ),
        migrations.AlterField(
            model_name='config',
            name='archived',
            field=models.BooleanField(default=False, help_text='Мягкое удаление. Архивная конфигурация никогда не ставится в очередь.', verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='config',
            name='collector_key',
            field=models.CharField(db_index=True, help_text='Ссылка по ключу. Конкретная версия фиксируется в момент постановки в очередь, а не здесь.', max_length=100, verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='config',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='config',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включена'),
        ),
        migrations.AlterField(
            model_name='config',
            name='last_job_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Последняя задача'),
        ),
        migrations.AlterField(
            model_name='config',
            name='last_run_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последний запуск'),
        ),
        migrations.AlterField(
            model_name='config',
            name='last_status',
            field=models.CharField(blank=True, choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='', editable=False, max_length=16, verbose_name='Последний статус'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='config',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_configs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='config',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Исходные параметры как их задал человек. При постановке в очередь они проверяются по схеме версии сборщика, и уже результат попадает в снимок задачи.', verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='config',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='config',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
        migrations.AlterField(
            model_name='job',
            name='attempt_no',
            field=models.PositiveIntegerField(default=0, help_text='Число передач между исполнителями, а не повторов сборщика. Растёт при каждом захвате, включая перехват после истечения аренды.', verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='job',
            name='available_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Доступна с'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='Запрошена отмена'),
        ),
        migrations.AlterField(
            model_name='job',
            name='claimed_by',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Захвачена воркером'),
        ),
        migrations.AlterField(
            model_name='job',
            name='claimed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Аренда до'),
        ),
        migrations.AlterField(
            model_name='job',
            name='collector_key',
            field=models.CharField(editable=False, max_length=100, verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='job',
            name='collector_version',
            field=models.CharField(editable=False, max_length=32, verbose_name='Версия сборщика'),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_id',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Мягкая ссылка. Внешнего ключа нет намеренно: история задач переживает жизненный цикл конфигурации.', verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_revision',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ревизия конфигурации'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='job',
            name='effective_parameters',
            field=models.JSONField(default=dict, editable=False, help_text='Параметры, разрешённые по схеме версии: подставлены умолчания, пройдена проверка. Только *ссылки* на учётные данные — никогда не сами секреты.', verbose_name='Итоговые параметры'),
        ),
        migrations.AlterField(
            model_name='job',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='job',
            name='fire_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='Запланированный момент, который реализует эта задача. Уникален в пределах расписания — именно это ограничение, а не блокировка, делает планирование идемпотентным.', null=True, verbose_name='Момент срабатывания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='{rows, bytes, calls, ...}', verbose_name='Метрики'),
        ),
        migrations.AlterField(
            model_name='job',
            name='origin',
            field=models.CharField(choices=[('manual', 'Вручную'), ('schedule', 'По расписанию')], default='manual', max_length=16, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.IntegerField(default=0, help_text='Больше — раньше.', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requested_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schema_version',
            field=models.IntegerField(default=0, editable=False, verbose_name='Версия схемы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начата'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='job',
            name='structured_error',
            field=models.JSONField(blank=True, help_text='{type, message, trace}', null=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='catchup_policy',
            field=models.CharField(choices=[('fire_missed', 'Догнать — поставить каждый пропущенный запуск'), ('skip_to_now', 'Только последний — пропустить всё, кроме ближайшего к текущему')], default='skip_to_now', help_text='Что делать с запусками, пропущенными пока система была недоступна.', max_length=16, verbose_name='После простоя'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='control.config', verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cron',
            field=models.CharField(help_text='Стандартное cron-выражение из пяти полей.', max_length=100, verbose_name='Cron'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, help_text='Сдвигается в той же транзакции, что создаёт задачу.', null=True, verbose_name='Последнее срабатывание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='overlap_policy',
            field=models.CharField(choices=[('skip', 'Пропустить — не запускать, пока идёт предыдущий запуск'), ('queue', 'В очередь — поставить в очередь за текущим запуском'), ('allow', 'Разрешить — запускать параллельно')], default='skip', help_text='Что делать, если предыдущий запуск этой конфигурации ещё не завершён.', max_length=16, verbose_name='При наложении'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Название по IANA. Моменты запуска считаются в этом поясе, хранятся в UTC.', max_length=64, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
