# Generated by Django 5.2.16 on 2026-07-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0002_alter_collector_options_alter_config_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[],
            options={
                "verbose_name": "Площадка",
                "verbose_name_plural": "Площадки",
                "ordering": ["name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("control.config",),
        ),
    ]
