# Generated by Django 5.2.16 on 2026-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Хост площадки.', max_length=255, verbose_name='Источник')),
                ('lot_id', models.CharField(max_length=255, verbose_name='Идентификатор лота')),
                ('trade_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Идентификатор торга')),
                ('lot_num', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер лота')),
                ('trade_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Номер торга')),
                ('trade_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип торгов')),
                ('debtor', models.TextField(blank=True, default='', verbose_name='Должник')),
                ('organizer', models.TextField(blank=True, default='', verbose_name='Организатор')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('lot_url', models.TextField(blank=True, default='', verbose_name='Ссылка на лот')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('price_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Цена как на сайте')),
                ('status', models.CharField(blank=True, default='', max_length=255, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, help_text='Выведено из статуса самой площадки, а не из присутствия лота в обходе.', verbose_name='Идут торги')),
                ('bidding_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Приём заявок до')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата результатов')),
                ('bidding_date_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Срок как на сайте')),
                ('event_date_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Дата как на сайте')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Документы')),
                ('price_schedule', models.JSONField(blank=True, default=list, verbose_name='График снижения цены')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Прочее с карточки')),
                ('fingerprint', models.CharField(blank=True, default='', help_text='Хэш табличных полей. Совпал — карточка лота не перезапрашивается.', max_length=64, verbose_name='Отпечаток')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Впервые увиден')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='Последний раз увиден')),
                ('last_job_id', models.BigIntegerField(blank=True, help_text='Мягкая ссылка, как и у Job на Config: лоты переживают чистку истории задач.', null=True, verbose_name='Последняя задача')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='lot_by_source_active_idx'), models.Index(fields=['-last_seen_at'], name='lot_by_last_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'lot_id'), name='uniq_lot_per_source')],
            },
        ),
    ]
