# Generated by Django 5.2.16 on 2026-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='collector_version',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schema_version',
        ),
        migrations.AlterField(
            model_name='job',
            name='effective_parameters',
            field=models.JSONField(default=dict, editable=False, help_text='Параметры, разрешённые по схеме сборщика: подставлены умолчания, пройдена проверка. Только *ссылки* на учётные данные — никогда не сами секреты.', verbose_name='Итоговые параметры'),
        ),
    ]
