# Generated by Django 5.2.16 on 2026-07-31 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0006_rename_platform_to_source"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Source",
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "domain",
                    models.URLField(
                        help_text="Корень сайта площадки со схемой и без завершающего слэша, например https://bankrupt.centerr.ru.",
                        verbose_name="Домен",
                    ),
                ),
                (
                    "listing_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Пусто — путь по умолчанию для движка того профиля, который обходит этот сайт.",
                        max_length=200,
                        verbose_name="Путь к листингу",
                    ),
                ),
                (
                    "extra_ca_cert",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Имя PEM-файла из collectors/certs с промежуточным сертификатом. Пусто — обычный набор корневых сертификатов.",
                        max_length=200,
                        verbose_name="Доп. сертификат",
                    ),
                ),
                (
                    "skip_tls_verify",
                    models.BooleanField(
                        default=False,
                        help_text="Полностью отключить проверку сертификата для этого сайта.",
                        verbose_name="Не проверять сертификат",
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Мягкое удаление. Профили, ссылающиеся на этот сайт, сохраняются.",
                        verbose_name="В архиве",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="config",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Сайт, чьи домен/путь листинга/TLS-настройки объединяются с параметрами этого профиля при постановке в очередь. Пусто — у сборщика нет понятия сайта.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="configs",
                to="control.source",
                verbose_name="Источник",
            ),
        ),
    ]
