# Generated by Django 5.2.16 on 2026-07-31 04:38

from django.db import migrations


class Migration(migrations.Migration):
    """D22: the «Источники» and «Конфигурации» tabs merge into one admin on `Config` itself.

    `DeleteModel(Source)` drops no table — `Source` was a proxy, `Config`'s table is untouched.
    It does drop the `add_source`/`change_source`/`delete_source`/`view_source` `Permission`
    rows and the `Source` `ContentType`; any grant made against those rows would need
    reassigning to the `*_config` codenames first, same caveat migration 0006 recorded for the
    `Platform` → `Source` rename.

    `AlterModelOptions` moves `Source`'s old `verbose_name`/`verbose_name_plural` onto `Config`,
    since `Config` is now what the merged tab is labelled after.
    """

    dependencies = [
        ("control", "0006_rename_platform_to_source"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Source",
        ),
        migrations.AlterModelOptions(
            name="config",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
            },
        ),
    ]
