# Generated by Django 5.2.17 on 2026-09-13 14:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="госномер"
                    ),
                ),
                ("model", models.CharField(max_length=64, verbose_name="модель")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("moving", "В движении"),
                            ("idle", "Стоянка"),
                            ("service", "На ТО"),
                            ("offline", "Нет связи"),
                        ],
                        default="idle",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="позиция"
                    ),
                ),
                (
                    "speed_kmh",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="скорость, км/ч"
                    ),
                ),
                (
                    "fuel_pct",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="топливо, %"
                    ),
                ),
                (
                    "odometer_km",
                    models.PositiveIntegerField(default=0, verbose_name="пробег, км"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="последний пакет",
                    ),
                ),
            ],
            options={
                "verbose_name": "транспорт",
                "verbose_name_plural": "транспорт",
                "ordering": ("plate",),
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="название")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("depot", "Депо"),
                            ("client", "Клиентская зона"),
                            ("restricted", "Запретная зона"),
                        ],
                        default="client",
                        max_length=16,
                        verbose_name="тип",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="контур"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="создана"
                    ),
                ),
            ],
            options={
                "verbose_name": "геозона",
                "verbose_name_plural": "геозоны",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="начало")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="окончание"
                    ),
                ),
                ("origin", models.CharField(max_length=120, verbose_name="откуда")),
                ("destination", models.CharField(max_length=120, verbose_name="куда")),
                (
                    "track",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326, verbose_name="трек"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=8,
                        verbose_name="расстояние, км",
                    ),
                ),
                (
                    "cargo_tons",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="груз, т",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="fleet.vehicle",
                        verbose_name="транспорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "рейс",
                "verbose_name_plural": "рейсы",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Инфо"),
                            ("warning", "Предупреждение"),
                            ("critical", "Критично"),
                        ],
                        default="info",
                        max_length=16,
                        verbose_name="уровень",
                    ),
                ),
                ("message", models.CharField(max_length=200, verbose_name="сообщение")),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="место"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="обработано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="время"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fleet.vehicle",
                        verbose_name="транспорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие",
                "verbose_name_plural": "события",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="home_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="fleet.zone",
                verbose_name="домашняя зона",
            ),
        ),
    ]
