# Generated by Django 5.2.17 on 2026-09-13 18:29

import control.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="имя"),
                ),
                (
                    "token",
                    models.CharField(
                        default=control.models.generate_token,
                        max_length=64,
                        unique=True,
                        verbose_name="токен",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
            ],
            options={
                "verbose_name": "раннер",
                "verbose_name_plural": "раннеры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="код"),
                ),
                (
                    "parser",
                    models.CharField(
                        help_text="Ключ парсера на стороне раннера, например example.news",
                        max_length=100,
                        verbose_name="парсер",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="параметры"
                    ),
                ),
                (
                    "cron",
                    models.CharField(
                        help_text="Пять полей cron, например «0 6,18 * * *» — в 06:00 и 18:00",
                        max_length=100,
                        validators=[control.models.validate_cron],
                        verbose_name="расписание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG — всё подряд"),
                            ("INFO", "INFO — обычный режим"),
                            ("WARNING", "WARNING — только проблемы"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="уровень логов",
                    ),
                ),
                (
                    "lease_seconds",
                    models.PositiveIntegerField(
                        default=600,
                        help_text="Если раннер не подаёт признаков жизни дольше — запуск считается просроченным",
                        verbose_name="аренда задания, с",
                    ),
                ),
                (
                    "max_failures",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="0 — не отключать автоматически",
                        verbose_name="отключить после N неудач",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(
                        default=0, verbose_name="неудач подряд"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="следующий запуск"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последний запуск"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменён"),
                ),
            ],
            options={
                "verbose_name": "источник",
                "verbose_name_plural": "источники",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_run_at"],
                        name="control_sou_is_acti_863fd7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("success", "Успех"),
                            ("failed", "Ошибка"),
                            ("expired", "Просрочен"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("schedule", "По расписанию"), ("manual", "Вручную")],
                        default="schedule",
                        max_length=16,
                        verbose_name="запуск",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="начало"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="окончание"
                    ),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="аренда до"
                    ),
                ),
                (
                    "items_total",
                    models.PositiveIntegerField(default=0, verbose_name="получено"),
                ),
                (
                    "items_new",
                    models.PositiveIntegerField(default=0, verbose_name="новых"),
                ),
                (
                    "items_updated",
                    models.PositiveIntegerField(default=0, verbose_name="обновлено"),
                ),
                (
                    "counters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="прочие счётчики"
                    ),
                ),
                (
                    "result_locator",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="результат"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="ошибка")),
                (
                    "warnings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="предупреждений"
                    ),
                ),
                (
                    "log_lines",
                    models.PositiveIntegerField(default=0, verbose_name="строк лога"),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="control.runner",
                        verbose_name="раннер",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="control.source",
                        verbose_name="источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "запуск",
                "verbose_name_plural": "запуски",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(verbose_name="номер строки")),
                ("ts", models.DateTimeField(verbose_name="время")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="уровень",
                    ),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="контекст"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="control.run",
                        verbose_name="запуск",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка лога",
                "verbose_name_plural": "логи запусков",
                "ordering": ("run", "seq"),
                "indexes": [
                    models.Index(
                        fields=["run", "seq"], name="control_run_run_id_a0bdad_idx"
                    ),
                    models.Index(
                        fields=["level", "ts"], name="control_run_level_0f3c1b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["status", "created_at"], name="control_run_status_3514a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["source", "-created_at"], name="control_run_source__490bfd_idx"
            ),
        ),
    ]
